version: 2

workflows:
  version: 2
  master:
    jobs:
      - build
      - deploy:
          context: develop
          requires:
            - build
          filters:
            branches:
              only:
                - features/EN-4-Deploy-ci

jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Install NPM packages
          command: npm install
      - run:
          name: Check the project (buid/lint/test)
          command: npm run check

  deploy:
    docker:
      - image: docker:20
    steps:
      - checkout
      - run:
          name: Testing
          command: echo $PORTAINER_LOGIN
      - run:
          name: Build image
          command: docker build -t envoys-backend .
