version: 2

workflows:
  version: 2
  master:
    jobs:
      - build
      - deploy:
          context: develop
          requires:
            - build
          filters:
            branches:
              only:
                - features/EN-4-Deploy-ci

jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Install NPM packages
          command: npm install
      - run:
          name: Check the project (buid/lint/test)
          command: npm run check

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker login
          command: docker login -u ${REGISTRY_LOGIN} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
      - run:
          name: Build docker image
          command: docker build -t envoys-backend .
      - run:
          name: Publish docker image
          command: |
            echo "Build number: ${CIRCLE_BUILD_NUM}"
            docker tag envoys-backend "registry.beta.envoys.vision/envoys-backend:develop-${CIRCLE_BUILD_NUM}"
            docker push "registry.beta.envoys.vision/envoys-backend:develop-${CIRCLE_BUILD_NUM}"
      - run:
          name: Run deploy
          command: ./.circleci/deploy.sh "${STACK_BACKEND}" "${CIRCLE_BUILD_NUM}"
