version: 2

jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Install NPM packages
          command: npm install
      - run:
          name: Check the project (buid/lint/test)
          command: npm run check

  deploy:
    docker:
      - image: cimg/base:stable
    context: develop
    filters:
      branches:
        only:
          - features/EN-4-Deploy-ci
    steps:
      - checkout
      - run:
          name: Build image
          command: docker build -t envoys-backend .
